---
title: Report on current update patterns
author: Anthony Davidson
---

# Overview

This report captures the ...

```{r echo = FALSE, message = FALSE, warning = FALSE}
library(here)
library(tidyverse)
```

## Exposure sites per update August

```{r echo = FALSE, message = FALSE, warning = FALSE}
# Exposure sites per Update for august
allfiles <- list.files("../data/allfiles/August/", pattern=c("table_", ".csv"), full.names = TRUE)

countsperupdate <- function(allfiles){
  
  allfiledat <- list() #<- list() MUST BE OUTSIDE

    for(i in 1:length(allfiles)) {
      tib <- read_csv(allfiles[i]) %>%
            dplyr::select(Contact, Date, Suburb)
      
    allfiledat[[i]] <- as.data.frame(tib)
  } #end loop
  
  return(allfiledat)
  
} #end function

##setup list of data
allfiledat <- list()

#run function
allfiledat <- countsperupdate(allfiles = allfiles)

res <- data.frame(update=NA, date=NA,locations=NA, contact=NA,nsites=NA )
cc<-1         

for(i in 1:length(allfiles)){
  
  dd <- allfiledat[[i]]         
  tt <- table(dd$Contact)
  
  if (length(tt)>0) {
  for (ii in 1:length(tt))
    {
    res[cc, 1] <- i
    res[cc,2] <- (substr(dd$Date[i], 1,10))
    res[cc,3] <- nrow(dd)
    res[cc,4] <- names(tt)[ii]
    res[cc,5] <- tt[ii]
    cc <- cc+1
    }
  }
}
  

res <- res[!res$contact=="Investigation information",]
res <- res[!res$contact=="Investigation location",]
res$contact <- factor(res$contact, levels=c("Close", "Casual","Monitor"))


res <- res[order(res$contact),]
cols <- c( "red", "yellow","blue")[as.numeric(res$contact)]

ggplot(res, aes(x=update,y=nsites))+geom_bar(stat="identity", position = "stack", width=1, aes(fill=contact))+
  xlab("update #")+
  ylab("# exposure sites")+
  ggtitle("Exposure sites over updates")

```


### September

```{r echo = FALSE, message = FALSE, warning = FALSE}
# Exposure sites per Update
allfiles <- list.files("../data/allfiles/September/", pattern=c("table_", ".csv"), full.names = TRUE)

# allfilesA <- list.files("../data/allfiles/August/", pattern=c("table_", ".csv"), full.names = TRUE)


countsperupdate <- function(allfiles){
  
  allfiledat <- list() #<- list() MUST BE OUTSIDE

    for(i in 1:length(allfiles)) {
      tib <- read_csv(allfiles[i]) %>%
            dplyr::select(Contact, Date, Suburb)
      
    allfiledat[[i]] <- as.data.frame(tib)
  } #end loop
  
  return(allfiledat)
  
} #end function

##setup list of data
allfiledat <- list()

#run function
allfiledat <- countsperupdate(allfiles = allfiles)

res <- data.frame(update=NA, date=NA,locations=NA, contact=NA,nsites=NA )
cc<-1         

for(i in 1:length(allfiles)){
  
  dd <- allfiledat[[i]]         
  tt <- table(dd$Contact)
  
  if (length(tt)>0) {
  for (ii in 1:length(tt))
    {
    res[cc, 1] <- i
    res[cc,2] <- (substr(dd$Date[i], 1,10))
    res[cc,3] <- nrow(dd)
    res[cc,4] <- names(tt)[ii]
    res[cc,5] <- tt[ii]
    cc <- cc+1
    }
  }
}
  


res <- res[!res$contact=="Investigation information",]
res <- res[!res$contact=="Investigation location",]
res$contact <- factor(res$contact, levels=c("Close", "Casual","Monitor"))


res <- res[order(res$contact),]
cols <- c( "red", "yellow","blue")[as.numeric(res$contact)]

ggplot(res, aes(x=update,y=nsites))+geom_bar(stat="identity", position = "stack", width=1, aes(fill=contact))+xlab("update #")+ylab("# exposure sites")+ggtitle("Exposure sites over updates")

```



